### ISSUE TITLE
suggestion: Add more sample code and test code

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#72] opened 2023-10-30 21:05 UTC
Current test coverage doesn't seem to be 100%

Suggest adding more test code and adding more examples to the documentation

The easiest place to spot this should be in Annotations, especially Union (and Optional)

**Comment by DanCardin** [comment] 2023-10-31 10:44
examples in the documentation can certainly be added, which is the actionable part of this issue, assuming I know the examples that would be relevant to you/a prospective user.

But the code coverage itself is already 100%, the problem is that the parser and the interactions between various parser features (even using the argparse backend) tend to simply require many examples of each different kind of interaction, that I dont know what i dont know. your prior bug report for example, is something I've never used before in my any of my own code 🤷

**Comment by wu-clan** [comment] 2023-10-31 17:31
Of course, this is a process of continuous improvement, and I shouldn't make requests without goals

**Comment by DanCardin** [comment] 2023-10-31 17:38
I'll close this for now, and commit to adding more as questions come up/maybe retroactively. Feel free to suggest more!

**Closed by DanCardin** 2023-10-31 17:38 UTC
